---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "data_bags"
  encrypted_data_bag_secret_key_path: ".encrypted_data_bag_secret"
  require_chef_omnibus: 12.3.0
  attributes:
    testkitchen: true
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[Chef-ProjectHaibung::default]
      - recipe[Chef-ProjectHaibung::users]
      - recipe[Chef-ProjectHaibung::api]
